export const apiKey = '560123213a8d40e08c8154414242401';

export const weatherImages = {
    'Ensoleillé': require('../assets/images/113.png'),
    'Clair': require('../assets/images/114.png'),
    'Partiellement nuageux': require('../assets/images/116.png'),
    'Nuageux': require('../assets/images/119.png'),
    'Couvert': require('../assets/images/122.png'),
    'Brume': require('../assets/images/143.png'),
    'Pluie éparse à proximité': require('../assets/images/176.png'),
    'Neige éparse à proximité': require('../assets/images/179.png'),
    'Grésil épars à proximité': require('../assets/images/182.png'),
    'Bruine verglaçante éparse à proximité': require('../assets/images/185.png'),
    'Foyers orageux à proximité': require('../assets/images/200.png'),
    'Rafales de neige': require('../assets/images/227.png'),
    'Blizzard': require('../assets/images/230.png'),
    'Brouillard': require('../assets/images/248.png'),
    'Brouillard givrant': require('../assets/images/260.png'),
    'Bruine légère éparse': require('../assets/images/263.png'),
    'Bruine légère': require('../assets/images/266.png'),
    'Bruine verglaçante': require('../assets/images/281.png'),
    'Forte bruine verglaçante': require('../assets/images/284.png'),
    'Pluie légère éparse': require('../assets/images/293.png'),
    'Pluie légère': require('../assets/images/296.png'),
    'Pluie modérée par moments': require('../assets/images/299.png'),
    'Pluie modérée': require('../assets/images/302.png'),
    'Pluie forte par moments': require('../assets/images/305.png'),
    'Pluie forte': require('../assets/images/308.png'),
    'Pluie verglaçante légère': require('../assets/images/311.png'),
    'Pluie verglaçante modérée à forte': require('../assets/images/314.png'),
    'Léger grésil': require('../assets/images/317.png'),
    'Grésil modéré à fort': require('../assets/images/320.png'),
    'Neige légère éparse': require('../assets/images/323.png'),
    'Neige légère': require('../assets/images/326.png'),
    'Neige modérée éparse': require('../assets/images/329.png'),
    'Neige modérée': require('../assets/images/332.png'),
    'Neige forte éparse': require('../assets/images/335.png'),
    'Neige forte': require('../assets/images/338.png'),
    'Cristaux de glace': require('../assets/images/350.png'),
    'Averse de pluie légère': require('../assets/images/353.png'),
    'Averse de pluie modérée': require('../assets/images/356.png'),
    'Averses de pluie torrentielle': require('../assets/images/359.png'),
    'Légères averses de grésil': require('../assets/images/362.png'),
    'Averses de grésil modérées à fortes': require('../assets/images/365.png'),
    'Légères averses de neige': require('../assets/images/368.png'),
    'Averses de neige modérées à fortes': require('../assets/images/371.png'),
    'Légères averses de cristaux de glace': require('../assets/images/374.png'),
    'Averses de cristaux de glace modérées à fortes': require('../assets/images/377.png'),
    'Légère pluie éparse avec tonnerre par endroit': require('../assets/images/386.png'),
    'Pluie forte à modérée avec tonerre par endroit': require('../assets/images/389.png'),
    'Légère neige éparse avec tonnerre par endroit': require('../assets/images/392.png'),
    'Neige éparse modérée à forte avec tonnerre par endroit': require('../assets/images/395.png')
};
